apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-frontend
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: glo7008/frontend:submission
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: srv-frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: srv-frontend
                port:
                  number: 80
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: srv-api-gateway
                port:
                  number: 8080
          - path: /analyze/sentence
            pathType: Prefix
            backend:
              service:
                name: srv-logic-api
                port:
                  number: 5000
          - path: /admin(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: srv-feedback-api
                port:
                  number: 9000
